// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUnvsWruyxpVfWP5slV65KvOlsIu1z6kI',
    appId: '1:83738585208:web:378ca6550dbbd1a88ba58d',
    messagingSenderId: '83738585208',
    projectId: 'music-e83e6',
    authDomain: 'music-e83e6.firebaseapp.com',
    storageBucket: 'music-e83e6.firebasestorage.app',
    measurementId: 'G-035N74T03D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1kQQxbevenTpEnaY1ycQ0N7UCZcpQFug',
    appId: '1:83738585208:android:0fea11b2a017d8038ba58d',
    messagingSenderId: '83738585208',
    projectId: 'music-e83e6',
    storageBucket: 'music-e83e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyOYU2ixQ4wta2tk9rBDVLy8-Mk5o6v6Y',
    appId: '1:83738585208:ios:ca7626e879651f978ba58d',
    messagingSenderId: '83738585208',
    projectId: 'music-e83e6',
    storageBucket: 'music-e83e6.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyOYU2ixQ4wta2tk9rBDVLy8-Mk5o6v6Y',
    appId: '1:83738585208:ios:ca7626e879651f978ba58d',
    messagingSenderId: '83738585208',
    projectId: 'music-e83e6',
    storageBucket: 'music-e83e6.firebasestorage.app',
    iosBundleId: 'com.example.musicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUnvsWruyxpVfWP5slV65KvOlsIu1z6kI',
    appId: '1:83738585208:web:6e3a93af76fa2cac8ba58d',
    messagingSenderId: '83738585208',
    projectId: 'music-e83e6',
    authDomain: 'music-e83e6.firebaseapp.com',
    storageBucket: 'music-e83e6.firebasestorage.app',
    measurementId: 'G-3SPCJYEG1J',
  );
}
